### ISSUE TITLE
POS UI Test Extension Failure

### ISSUE THREAD

**Issue by dmhenry** [Shopify/shopify-cli-extensions#352]
`make serve-dev testdata/extension.config.yml` errors out with:

```
POS UI Test Extension (Error building extension:  Error: Build failed with 1 error:
src/index.tsx:2:16: error: No matching export in "node_modules/@shopify/retail-ui-extensions-react/index.mjs" for import "useExtensionApi"
    at failureErrorWithLog (/Users/dave/src/github.com/Shopify/shopify-cli-extensions/tmp/pos_ui_extension/node_modules/esbuild/lib/main.js:1475:15)
    at /Users/dave/src/github.com/Shopify/shopify-cli-extensions/tmp/pos_ui_extension/node_modules/esbuild/lib/main.js:1133:28
    at runOnEndCallbacks (/Users/dave/src/github.com/Shopify/shopify-cli-extensions/tmp/pos_ui_extension/node_modules/esbuild/lib/main.js:1051:65)
    at buildResponseToResult (/Users/dave/src/github.com/Shopify/shopify-cli-extensions/tmp/pos_ui_extension/node_modules/esbuild/lib/main.js:1131:7)
    at /Users/dave/src/github.com/Shopify/shopify-cli-extensions/tmp/pos_ui_extension/node_modules/esbuild/lib/main.js:1240:14
    at /Users/dave/src/github.com/Shopify/shopify-cli-extensions/tmp/pos_ui_extension/node_modules/esbuild/lib/main.js:611:9
    at handleIncomingPacket (/Users/dave/src/github.com/Shopify/shopify-cli-extensions/tmp/pos_ui_extension/node_modules/esbuild/lib/main.js:708:9)
    at Socket.readFromStdout (/Users/dave/src/github.com/Shopify/shopify-cli-extensions/tmp/pos_ui_extension/node_modules/esbuild/lib/main.js:578:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/@shopify/retail-ui-extensions-react/index.mjs" for import "useExtensionApi"'
    }
  ],
  warnings: []
})
```

**Comment by dmhenry** [comment]
CC: @samiulmonir06

**Comment by dmhenry** [comment]
@samiulmonir06 Would you mind linking to the issue on your end? Feel free to close this afterward.
