### ISSUE TITLE
Build failure `Could not resolve "@shopify/admin-ui-extensions/extension-points"`

### ISSUE THREAD

**Issue by paweltatarczuk** [Shopify/shopify-cli-extensions#383]
Creating an extension with `shopify app scaffold extension` (selecting "Subscription UI" and "React") ends up with build failures:

```
Error building extension:  Error: Build failed with 6 errors:
../../node_modules/@shopify/admin-ui-extensions-react/build/esm/extension-api/ContainerApi/index.mjs:1:31: error: Could not resolve "@shopify/admin-ui-extensions/extension-api" (mark it as external to exclude it from the bundle)
../../node_modules/@shopify/admin-ui-extensions-react/build/esm/extension-api/DataApi/index.mjs:1:26: error: Could not resolve "@shopify/admin-ui-extensions/extension-api" (mark it as external to exclude it from the bundle)
../../node_modules/@shopify/admin-ui-extensions-react/build/esm/extension-api/SessionTokenApi/index.mjs:1:34: error: Could not resolve "@shopify/admin-ui-extensions/extension-api" (mark it as external to exclude it from the bundle)
../../node_modules/@shopify/admin-ui-extensions-react/build/esm/extension-api/ToastApi/index.mjs:1:27: error: Could not resolve "@shopify/admin-ui-extensions/extension-api" (mark it as external to exclude it from the bundle)
../../node_modules/@shopify/admin-ui-extensions-react/build/esm/index.mjs:1:14: error: Could not resolve "@shopify/admin-ui-extensions/extension-points" (mark it as external to exclude it from the bundle)
...
    at failureErrorWithLog (/Users/foo/www/playground/subscriptions/node_modules/@shopify/shopify-cli-extensions/node_modules/esbuild/lib/main.js:1475:15)
    at /Users/foo/www/playground/subscriptions/node_modules/@shopify/shopify-cli-extensions/node_modules/esbuild/lib/main.js:1133:28
    at runOnEndCallbacks (/Users/foo/www/playground/subscriptions/node_modules/@shopify/shopify-cli-extensions/node_modules/esbuild/lib/main.js:1051:65)
    at buildResponseToResult (/Users/foo/www/playground/subscriptions/node_modules/@shopify/shopify-cli-extensions/node_modules/esbuild/lib/main.js:1131:7)
    at /Users/foo/www/playground/subscriptions/node_modules/@shopify/shopify-cli-extensions/node_modules/esbuild/lib/main.js:1240:14
    at /Users/foo/www/playground/subscriptions/node_modules/@shopify/shopify-cli-extensions/node_modules/esbuild/lib/main.js:611:9
    at handleIncomingPacket (/Users/foo/www/playground/subscriptions/node_modules/@shopify/shopify-cli-extensions/node_modules/esbuild/lib/main.js:708:9)
    at Socket.readFromStdout (/Users/foo/www/playground/subscriptions/node_modules/@shopify/shopify-cli-extensions/node_modules/esbuild/lib/main.js:578:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
```

Here's the log excerpt of esbuild with `logLevel` set to `debug`:

```
 > debug: Resolving import "@shopify/admin-ui-extensions/extension-points" in directory "/Users/foo/www/playground/subscriptions/node_modules/@shopify/admin-ui-extensions-react/build/esm" of type "import-statement"
   note: Read 4 entries for directory "/Users/foo/www/playground/subscriptions/node_modules/@shopify/admin-ui-extensions-react/build/esm"
   note: No "browser" map found in directory "/Users/foo/www/playground/subscriptions/node_modules/@shopify/admin-ui-extensions-react/build/esm"
   note: Searching for "@shopify/admin-ui-extensions/extension-points" in "node_modules" directories starting from "/Users/foo/www/playground/subscriptions/node_modules/@shopify/admin-ui-extensions-react/build/esm"
   note:   Parsed package name "@shopify/admin-ui-extensions" and package subpath "./extension-points"
   note:   Checking for a package in the directory "/Users/foo/www/playground/subscriptions/node_modules/@shopify/admin-ui-extensions/extension-points"
   note:   Read 9 entries for directory "/Users/foo/www/playground/subscriptions/node_modules/@shopify"
   note:   The file "/Users/foo/www/playground/subscriptions/node_modules/@shopify/admin-ui-extensions/package.json" exists
   note:   Read 18 entries for directory "/Users/foo/www/playground/subscriptions/node_modules/@shopify/admin-ui-extensions"
   note:   Looking for "./extension-points" in "exports" map in "/Users/foo/www/playground/subscriptions/node_modules/@shopify/admin-ui-extensions/package.json"
   note:     Checking object path map for "./extension-points"
   note:     The key "./*" matched with "extension-points" left over
   note:     Checking path "extension-points" against target "./*"
   note:       Substituted "extension-points" for "*" in "./*" to get "./extension-points"
   note:     The resolved path "/Users/foo/www/playground/subscriptions/node_modules/@shopify/admin-ui-extensions/extension-points" is exact
   note:     Read 18 entries for directory "/Users/foo/www/playground/subscriptions/node_modules/@shopify/admin-ui-extensions"
```

Versions

Node: 14.18.2
npm: 6.14.15
@shopify/admin-ui-extensions-react: 1.0.2
@shopify/app: 3.13.1
@shopify/cli: 3.13.1
react: ^17.0.2

**Comment by paweltatarczuk** [comment]
According to this error:

```
 > ../../node_modules/@shopify/admin-ui-extensions-react/build/esm/extension-api/SessionTokenApi/index.mjs:1:34: error: Could not resolve "@shopify/admin-ui-extensions/extension-api" (mark it as external to exclude it from the bundle)
     1 │ import { isSessionTokenApi } from '@shopify/admin-ui-extensions/extension-api';
       ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   ../../node_modules/@shopify/admin-ui-extensions/package.json:40:11: note: The module "./extension-api" was not found on the file system
    40 │     "./*": "./*"
       ╵            ~~~~~
```

Seems like it's related to this block in `@shopify/admin-ui-extensions`:

```
  "exports": {
    ".": {
      "esnext": "./index.esnext",
      "import": "./index.mjs",
      "require": "./index.js"
    },
    "./*": "./*"
  },
```

After changing this block to I'm able to successfully build the extension:

```
  "exports": {
    ".": {
      "esnext": "./index.esnext",
      "import": "./index.mjs",
      "require": "./index.js"
    },
    "./*": {
      "esnext": "./*.esnext",
      "import": "./*.mjs",
      "require": "./*.js"
    }
  },
```

Seems like `@shopify/admin-ui-extensions` is a private repo so I can't post an issue there or open up a PR though.

**Comment by vividviolet** [comment]
@paweltatarczuk the repo for this package lives [here](https://github.com/Shopify/ui-extensions) - can you please open up an issue there?

**Comment by MaxCloutier** [comment]
@paweltatarczuk The fix has been deployed and after testing, the build failure no longer happens.

**Comment by paweltatarczuk** [comment]
Thank you!
